site_name: "Prefeitura de Verdelândia"
theme:
  name: material
  logo: assets/logo.png
  language: pt
  palette:
    primary: spring green
    accent: spring green

extra_css:
  - style.css

nav:
  - Início: index.md
  - I. Planejamento do Projeto e Processo de Design:
    - Planejamento do Projeto:
      - Cronograma do Projeto: documentos/Cronograma.md
      - Metodologia: documentos/Metodologia.md
      - Ferramentas: documentos/Ferramentas.md
      - Sites Avaliados: documentos/SitesAvaliados.md
      - Site Escolhido: documentos/SiteEscolhido.md
    - Processos de Design: documentos/Processos.md
  - II. Perfil do usuário, Personas e Análise de tarefas:
    - Análise de Tarefas:
      - Análise de Tarefas: documentos/AnaliseTarefas.md
      - Análise Hierárquica de Tarefas (AHT): documentos/AnaliseHierarquica.md
    - Personas: documentos/Personas.md
    - Perfil do Usuário: documentos/PerfilUsuario.md
  - Apresentações:
      - Ponto de controle 1: documentos/Apresentacao_PC1.md
