site_name: "Prefeitura de Verdelândia"
theme:
  name: material
  logo: assets/logos/logo.png
  language: pt
  palette:
    primary: spring green
    accent: spring green

extra_css:
  - style.css

nav:
  - Início: index.md
  - I. Planejamento do Projeto e Processo de Design:
    - Planejamento do Projeto:
      - Cronograma do Projeto: documentos/01-Planejamento-e-Processo/Cronograma.md
      - Metodologia: documentos/01-Planejamento-e-Processo/Metodologia.md
      - Ferramentas: documentos/01-Planejamento-e-Processo/Ferramentas.md
      - Sites Avaliados: documentos/01-Planejamento-e-Processo/SitesAvaliados.md
      - Site Escolhido: documentos/01-Planejamento-e-Processo/SiteEscolhido.md
    - Processos de Design: documentos/01-Planejamento-e-Processo/Processos.md

  - II. Perfil do usuário, Personas e Análise de tarefas:
    - Perfil do Usuário: documentos/02-Perfil-Persona-Analise/PerfilUsuario.md
    - Personas: documentos/02-Perfil-Persona-Analise/Personas.md
    - Análise de Tarefas:
      - Análise de Tarefas: documentos/02-Perfil-Persona-Analise/AnaliseTarefas.md
      - Análise Hierárquica de Tarefas (AHT): documentos/02-Perfil-Persona-Analise/AnaliseHierarquica.md

  - III. Metas de Usabilidade e Guias de Estilo:
    - Princípios Gerais: documentos/03-Principios-Metas-Guia/PrincipiosGerais.md
    - Metas de Usabilidade: documentos/03-Principios-Metas-Guia/MetasUsabilidade.md
    - Guia de Estilos: documentos/03-Principios-Metas-Guia/GuiaDeEstilos.md
    
  - IV. Planejamento da Avaliação do Storyboard e Análise de tarefas:
    - Análise de Tarefas:
      - Planejamento de Análise de Tarefas: documentos/04-Planejamento-Avaliacao-Storyboard-Analise-tarefas/AnaliseTarefas/PlanejamentoAnaliseTarefas.md
    - Storyboard:
      - Storyboard: documentos/04-Planejamento-Avaliacao-Storyboard-Analise-tarefas/StoryBoard/Storyboard.md
      - Planejamento da Avaliação do Storyboard: documentos/04-Planejamento-Avaliacao-Storyboard-Analise-tarefas/StoryBoard/PlanejamentoAvaliacaoStoryboard.md
  
  - V. Relato dos Resultados do Planejamento da Avaliação do Storyboard e Analise de Tarefas:
    - Resultado Análise de Tarefas: documentos/05-Relato-Resultado-Planejamento-do-Storyboard-Analise-tarefas/ResultadoAnaliseTarefas.md
    - Resultado Storyboard: documentos/05-Relato-Resultado-Planejamento-do-Storyboard-Analise-tarefas/ResultadoStoryboard.md
    - Planejamento do protótipo em papel: documentos/05-Relato-Resultado-Planejamento-do-Storyboard-Analise-tarefas/PlanejamentoPrototipoPapel.md

  - VI. Verificação:
    - Introdução: documentos/06-Verificacao/Introducao.md
    - I:
      - Cronograma do Projeto: documentos/06-Verificacao/01-Planejamento-e-Processo/Cronograma.md
      - Metodologia: documentos/06-Verificacao/01-Planejamento-e-Processo/Metodologia.md
      - Ferramentas: documentos/06-Verificacao/01-Planejamento-e-Processo/Ferramentas.md
      - Sites Avaliados: documentos/06-Verificacao/01-Planejamento-e-Processo/SitesAvaliados.md
      - Site Escolhido: documentos/06-Verificacao/01-Planejamento-e-Processo/SiteEscolhido.md
      - Processos de Design: documentos/06-Verificacao/01-Planejamento-e-Processo/Processos.md
    - II:
      - Perfil do Usuário: documentos/06-Verificacao/02-Perfil-Persona-Analise/PerfilUsuario.md
      - Personas: documentos/06-Verificacao/02-Perfil-Persona-Analise/Personas.md
      - Análise de Tarefas: documentos/06-Verificacao/02-Perfil-Persona-Analise/AnaliseTarefas.md
      - Análise Hierárquica de Tarefas (AHT): documentos/06-Verificacao/02-Perfil-Persona-Analise/AnaliseHierarquica.md
    - III:
      - Principios Gerais: documentos/06-Verificacao/03-Principios-Metas-Guia/GuiaDeEstilos.md
      - Metas de Usabilidade: documentos/06-Verificacao/03-Principios-Metas-Guia/MetasUsabilidade.md
      - Guia de Estilos: documentos/06-Verificacao/03-Principios-Metas-Guia/GuiaDeEstilos.md
    - IV:
      - Planejamento de Análise de Tarefas: documentos/06-Verificacao/04-Planejamento-Avaliacao-Storyboard-Analise-tarefas/PlanejamentoAnaliseTarefas.md
      - Storyboard: documentos/06-Verificacao/04-Planejamento-Avaliacao-Storyboard-Analise-tarefas/Storyboard.md
      - Planejamento da Avaliação do Storyboard: documentos/06-Verificacao/04-Planejamento-Avaliacao-Storyboard-Analise-tarefas/PlanejamentoAvaliacaoStoryboard.md
    - V:
      - Resultado Análise de Tarefas: documentos/06-Verificacao/05-Relato-Resultado-Planejamento-do-Storyboard-Analise-tarefas/ResultadoAnaliseTarefas.md
      - Resultado Storyboard: documentos/06-Verificacao/05-Relato-Resultado-Planejamento-do-Storyboard-Analise-tarefas/ResultadoStoryboard.md
      - Planejamento do protótipo em papel: documentos/06-Verificacao/05-Relato-Resultado-Planejamento-do-Storyboard-Analise-tarefas/PlanejamentoPrototipoPapel.md

  - VII. Relato dos resultados do protótipo de baixa fidelidade e Planejamento da Avaliação do protótipo de alta fidelidade: 
      - Planejamento da Avaliação do Protótipo de Alta Fidelidade: documentos/07-Resultado-Prototipo-Papel-Planejamento-Prototipo-Alta-Fidelidade/PlanejamentoPrototipoAltaFidelidade.md
      - Entrevistas do Protótipo de Papel: documentos/07-Resultado-Prototipo-Papel-Planejamento-Prototipo-Alta-Fidelidade/EntrevistasDoProtótipoDePapel.md
      - Relato dos Resultados do Protótipo de Papel: documentos/07-Resultado-Prototipo-Papel-Planejamento-Prototipo-Alta-Fidelidade/RelatoDosResultadosDoProtótipoDePapel.md  

  - VIII. Protótipo de Alta Fidelidade:
    - Protótipo: documentos/08-Prototipo-Alta-Fidelidade/PrototipoAltaFidelidade.md

  - Apresentações:
    - Ponto de controle 1: documentos/Apresentações/Apresentacao_PC1.md
    - Ponto de controle 2: documentos/Apresentações/Apresentacao_PC2.md
    - Ponto de controle 3: documentos/Apresentações/Apresentacao_PC3.md
    - Ponto de controle 4: documentos/Apresentações/Apresentacao_PC4.md
    - Ponto de controle 5: documentos/Apresentações/Apresentacao_PC5.md
    - Ponto de controle 6: documentos/Apresentações/Apresentacao_PC6.md
    - Ponto de controle 7: documentos/Apresentações/Apresentacao_PC7.md