site_name: "Prefeitura de Verdelândia"
theme:
  name: material
  logo: assets/logo.png
  language: pt
  palette:
    primary: spring green
    accent: spring green

extra_css:
  - style.css

nav:
  - Início: index.md
  - Documentação:
      - Cronograma do Projeto: documentos/Cronograma.md
      - Metodologia: documentos/Metodologia.md
      - Ferramentas: documentos/Ferramentas.md
      - Processos: documentos/Processos.md
  - Planejamento:
      - Sites Avaliados: documentos/SitesAvaliados.md
      - Site Escolhido: documentos/SiteEscolhido.md
  - Apresentações:
      - Ponto de controle 1: documentos/Apresentacao_PC1.md
